## LIBRERIE ESTERNE, LIBRERIE STANDARD, NUMPY, PANDAS

In [11]:
import numpy as np
import pandas as pd
import math

In [12]:
# Abbiamo una lista di liste.
# Che tipo di struttura dati o matematica potrebbe rappresentare? 
# Notare che tutte le liste "interne" sono della stessa dimensione Come facciamo per accedere ad un elemento in particolare?

mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
mat_array = np.array(mat)
mat_array

#2darray composto da 3 righe e 5 colonne

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
#shape
mat_array.shape

(3, 5)

In [14]:
#accesso alla prima riga
mat_array[0,:]

array([0, 1, 2, 3, 4])

In [15]:
#accesso alle ultime due righe
mat_array[-2:,:]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
#accesso ad una singola colonna
mat_array[:,0]

array([ 0,  5, 10])

In [17]:
#accesso a un singolo valore
mat_array[0,1]

1

In [28]:
# Importiamo il modulo math e proviamo a usare le funzioni .sin() .cos() .factorial() e la variabile .pi la riconoscete?
print(math.sin(15), "-", math.cos(25), "-", math.factorial(3), "-", math.pi ) #pi è il pigreco

0.6502878401571168 - 0.9912028118634736 - 6 - 3.141592653589793


In [30]:
# Proviamo a eseguire math.degrees(math.pi) 
# Qual è e cosa significa il risultato? Per saperne di più su questa funzione possiamo usare help(math.degrees)

math.degrees(math.pi) #Convert angles from radians to degrees

180.0

In [52]:
# L'azienda Object SpA ha creato una lista di quanti oggetti ha venduto ogni mese nell'ultimo anno:
# lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]
# trasformiamola in un array NumPy (casting):

lst = np.array([2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350])
max_sales = lst.max()
sales_4999 = lst[lst > 4999]
sales_3000 = lst[lst < 3000]
avg_sales = lst.mean()

print("Vendita massima:", max_sales)
print("Vendite > di 4999:", sales_4999, "Numero vendite:", len(sales_4999))
print("Vendite > di 3000:", sales_3000)
print("Vendite medie:", round(avg_sales,2))

Vendita massima: 8150
Vendite > di 4999: [5500 7200 6410 8150 7100 5350] Numero vendite: 6
Vendite > di 3000: [2000 1280 1900 2500]
Vendite medie: 4634.17


In [53]:
# Dunque qual è la differenza tra i due tipi di dato? Cosa potremmo fare con la Series che non possiamo fare con il dizionario?
fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000}
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000], index=range(1997, 2005))

In [54]:
fatturati_dict

{1997: 12000,
 1998: 15000,
 1999: 20000,
 2000: 23000,
 2001: 25000,
 2002: 17000,
 2003: 14000,
 2004: 21000}

In [55]:
fatturati_series

1997    12000
1998    15000
1999    20000
2000    23000
2001    25000
2002    17000
2003    14000
2004    21000
dtype: int64

In [57]:
#il dizionario è composto da una coppia chiave: valore.
#gli elementi sono accessibili tramite la sintassi chiave[valore]
#i valori nella serie sono stanziati in un array e l'accesso avviene tramite indice (funzioni iloc e loc)

print(fatturati_dict[1997],"-",fatturati_series.loc[1997])

12000 - 12000


In [59]:
# L'azienda Object SpA ha un dataset con tutti gli stipendi dei dipendenti, memorizzato in un ndarray:
stipendi = np.array([100, 200, 300, 400, 500,  600, 700, 800, 900, 1000])

In [63]:
#raddoppio gli stipendi:
#1 sol:
stipendi2 = []
for stipendio in stipendi:
    stipendi2.append(stipendio*2)
print(stipendi2)

#2 sol:
stipendi2 = stipendi * 2
print(stipendi2)

#3sol:
stipendi2 = [x*2 for x in stipendi]
print(stipendi2)

[200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]
[ 200  400  600  800 1000 1200 1400 1600 1800 2000]
[200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]
